name: Crowdin Action
on:
    workflow_dispatch:
jobs:
    crowdin:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Synchronize with Crowdin
            uses: crowdin/github-action@v2
            with:
                download_translations: true
                config: '.github/crowdin.yml'
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
